[LHR 코드 11-1]

In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (8,927 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package fonts-nanum.
(Reading database ... 121703 files and dire

[LHR 코드 11-2]

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

몸무게 = [30, 35, 40]
팔길이 = [45, 50, 55]

데이터 = np.array([몸무게, 팔길이]).T

scaler = MinMaxScaler()
정규화_데이터 = scaler.fit_transform(데이터)

print("=== 원본 데이터 ===")
print(데이터)

print("\n=== 정규화된 데이터 ===")
print(정규화_데이터)


=== 원본 데이터 ===
[[30 45]
 [35 50]
 [40 55]]

=== 정규화된 데이터 ===
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


[LHR 코드 11-3]

In [3]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

키 = [155, 160, 165, 170, 175]
신발 = [230, 240, 250, 260, 270]

원본_데이터 = np.array([키, 신발]).T

print("=== 원본 데이터 ===")
print("   키   신발크기")
print(원본_데이터)


=== 원본 데이터 ===
   키   신발크기
[[155 230]
 [160 240]
 [165 250]
 [170 260]
 [175 270]]


[LHR 코드 11-4]

In [4]:
pca = PCA(n_components=2)
pca.fit(원본_데이터)
변환된_데이터 = pca.transform(원본_데이터)

print("\n=== 변환된 데이터 ===")
print("   제1주성분    제2주성분")
print(np.round(변환된_데이터, 2))



=== 변환된 데이터 ===
   제1주성분    제2주성분
[[-22.36  -0.  ]
 [-11.18   0.  ]
 [  0.     0.  ]
 [ 11.18  -0.  ]
 [ 22.36  -0.  ]]


[LHR 코드 11-5]

In [5]:
설명력 = pca.explained_variance_ratio_

print("\n=== PCA 설명력 ===")
print(f"제1주성분의 설명력: {설명력[0]:.2%}")
print(f"제2주성분의 설명력: {설명력[1]:.2%}")



=== PCA 설명력 ===
제1주성분의 설명력: 100.00%
제2주성분의 설명력: 0.00%


[LHR 코드 11-6]

In [6]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

나이 = [8, 9, 10, 11, 12]
시청시간 = [3.0, 2.5, 2.0, 1.5, 1.0]

원본_데이터 = np.array([나이, 시청시간]).T

print("\n=== 원본 데이터 ===")
print("   나이   TV시청시간")
print(원본_데이터)



=== 원본 데이터 ===
   나이   TV시청시간
[[ 8.   3. ]
 [ 9.   2.5]
 [10.   2. ]
 [11.   1.5]
 [12.   1. ]]


[LHR 코드 11-7]

In [7]:
pca = PCA(n_components=2)
pca.fit(원본_데이터)
변환된_데이터 = pca.transform(원본_데이터)

print("\n=== 변환된 데이터 ===")
print("   제1주성분   제2주성분")
print(np.round(변환된_데이터, 2))



=== 변환된 데이터 ===
   제1주성분   제2주성분
[[-2.24  0.  ]
 [-1.12  0.  ]
 [ 0.    0.  ]
 [ 1.12  0.  ]
 [ 2.24  0.  ]]


[LHR 코드 11-8]

In [8]:
설명력 = pca.explained_variance_ratio_

print("\n=== PCA 설명력 ===")
print(f"제1주성분의 설명력: {설명력[0]:.2%}")
print(f"제2주성분의 설명력: {설명력[1]:.2%}")



=== PCA 설명력 ===
제1주성분의 설명력: 100.00%
제2주성분의 설명력: 0.00%


[LHR 코드 11-9]

In [9]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

수학 = [50, 65, 80, 90, 100]
과학 = [45, 60, 75, 85, 95]
영어 = [40, 55, 70, 80, 90]

원본_데이터 = np.array([수학, 과학, 영어]).T

print("\n=== 원본 데이터 ===")
print("   수학  과학  영어")
print(원본_데이터)



=== 원본 데이터 ===
   수학  과학  영어
[[ 50  45  40]
 [ 65  60  55]
 [ 80  75  70]
 [ 90  85  80]
 [100  95  90]]


[LHR 코드 11-10]

In [10]:
pca = PCA(n_components=3)
변환된_데이터 = pca.fit_transform(원본_데이터)

print("\n=== 변환된 데이터 ===")
print("   제1주성분   제2주성분   제3주성분")
print(np.round(변환된_데이터, 2))



=== 변환된 데이터 ===
   제1주성분   제2주성분   제3주성분
[[-46.77  -0.     0.  ]
 [-20.78   0.     0.  ]
 [  5.2   -0.     0.  ]
 [ 22.52   0.     0.  ]
 [ 39.84   0.     0.  ]]


[LHR 코드 11-11]

In [11]:
설명력 = pca.explained_variance_ratio_

print("\n=== PCA 설명력 ===")
print(f"제1주성분의 설명력: {설명력[0]:.2%}")
print(f"제2주성분의 설명력: {설명력[1]:.2%}")
print(f"제3주성분의 설명력: {설명력[2]:.2%}")



=== PCA 설명력 ===
제1주성분의 설명력: 100.00%
제2주성분의 설명력: 0.00%
제3주성분의 설명력: 0.00%


[LHR 코드 11-12]

In [12]:
X_pca = 변환된_데이터[:, 0].reshape(-1, 1)
Y = np.array(영어)

linear_model = LinearRegression()
linear_model.fit(X_pca, Y)

기울기 = linear_model.coef_[0]
절편 = linear_model.intercept_

print("\n=== PCA 기반 선형 회귀 분석 결과 ===")
print(f"회귀식: 영어점수 = {기울기:.2f} * 제1주성분 + {절편:.2f}")



=== PCA 기반 선형 회귀 분석 결과 ===
회귀식: 영어점수 = 0.58 * 제1주성분 + 67.00


[LHR 코드 11-13]

In [13]:
새로운_데이터 = np.array([[40, 35, 30]])
새로운_데이터_pca = pca.transform(새로운_데이터)[:, 0]

예측값 = linear_model.predict(새로운_데이터_pca.reshape(-1, 1))

print(f"\n수학,과학,영어=40,35,30에 해당하는 제1주성분 값으로 예측한 영어점수: {예측값[0]:.2f}점")



수학,과학,영어=40,35,30에 해당하는 제1주성분 값으로 예측한 영어점수: 30.00점


[LHR 코드 11-14]

In [14]:
from google.colab import files
uploaded = files.upload()

Saving LHR_titanic_nomissing.csv to LHR_titanic_nomissing.csv


[LHR 코드 11-15]

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

df = pd.read_csv('LHR_titanic_nomissing.csv')
numeric_features = df[['Age', 'Fare', 'SibSp', 'Parch']]

print("=== 원본 데이터 ===")
print(numeric_features)


=== 원본 데이터 ===
           Age     Fare  SibSp  Parch
0    22.000000   7.2500      1      0
1    38.000000  71.2833      1      0
2    26.000000   7.9250      0      0
3    35.000000  53.1000      1      0
4    35.000000   8.0500      0      0
..         ...      ...    ...    ...
884  27.000000  13.0000      0      0
885  19.000000  30.0000      0      0
886  29.699118  23.4500      1      2
887  26.000000  30.0000      0      0
888  32.000000   7.7500      0      0

[889 rows x 4 columns]


[LHR 코드 11-16]

In [17]:
scaler = MinMaxScaler()
normalized_features = scaler.fit_transform(numeric_features)

print("=== 정규화된 데이터 ===")
print(normalized_features)


=== 정규화된 데이터 ===
[[0.27117366 0.01415106 0.125      0.        ]
 [0.4722292  0.13913574 0.125      0.        ]
 [0.32143755 0.01546857 0.         0.        ]
 ...
 [0.36792055 0.04577135 0.125      0.33333333]
 [0.32143755 0.0585561  0.         0.        ]
 [0.39683338 0.01512699 0.         0.        ]]


[LHR 코드 11-17]

In [18]:
pca = PCA()
pca_features = pca.fit_transform(normalized_features)

print("\n=== 변환된 데이터 (4차원) ===")
print("1주성분  2주성분  3주성분  4주성분")
print(np.round(pca_features, 4))



=== 변환된 데이터 (4차원) ===
1주성분  2주성분  3주성분  4주성분
[[-0.0661 -0.0863  0.0843 -0.0165]
 [ 0.0672  0.0884  0.0837  0.0716]
 [ 0.0355 -0.1057 -0.002  -0.0158]
 ...
 [-0.1568  0.1564 -0.1346 -0.0966]
 [ 0.0328 -0.0934 -0.0083  0.0249]
 [ 0.0885 -0.0537  0.0047 -0.0273]]


[LHR 코드 11-18]

In [19]:
설명력 = pca.explained_variance_ratio_

print("\n=== PCA 설명력 ===")
print(f"제1주성분의 설명력: {설명력[0]:.2%}")
print(f"제2주성분의 설명력: {설명력[1]:.2%}")
print(f"제3주성분의 설명력: {설명력[2]:.2%}")
print(f"제4주성분의 설명력: {설명력[3]:.2%}")



=== PCA 설명력 ===
제1주성분의 설명력: 45.14%
제2주성분의 설명력: 28.76%
제3주성분의 설명력: 14.88%
제4주성분의 설명력: 11.22%


[LHR 코드 11-19]

In [20]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

키 = [150, 155, 160, 165, 170]
몸무게 = [40, 48, 55, 63, 70]
발크기 = [220, 230, 240, 250, 260]

원본_데이터 = np.array([키, 몸무게, 발크기]).T

print("=== 원본 데이터 ===")
print("키   몸무게   발크기")
print(원본_데이터)


=== 원본 데이터 ===
키   몸무게   발크기
[[150  40 220]
 [155  48 230]
 [160  55 240]
 [165  63 250]
 [170  70 260]]


[LHR 코드 11-20]

In [21]:
scaler = MinMaxScaler()

normalized_features = scaler.fit_transform(원본_데이터)

print("=== 정규화된 데이터 ===")
print(normalized_features)


=== 정규화된 데이터 ===
[[0.         0.         0.        ]
 [0.25       0.26666667 0.25      ]
 [0.5        0.5        0.5       ]
 [0.75       0.76666667 0.75      ]
 [1.         1.         1.        ]]


[LHR 코드 11-21]

In [22]:
pca = PCA(n_components=2)

변환된_데이터 = pca.fit_transform(normalized_features)

print("\n=== 변환된 데이터 (2차원) ===")
print(" 제1주성분  제2주성분")
print(np.round(변환된_데이터, 2))



=== 변환된 데이터 (2차원) ===
 제1주성분  제2주성분
[[-0.87 -0.01]
 [-0.43  0.01]
 [-0.   -0.01]
 [ 0.44  0.01]
 [ 0.86 -0.01]]


[LHR 코드 11-22]

In [23]:
설명력 = pca.explained_variance_ratio_

print("\n=== PCA 설명력 ===")
print(f"제1주성분의 설명력: {설명력[0]:.2%}")
print(f"제2주성분의 설명력: {설명력[1]:.2%}")



=== PCA 설명력 ===
제1주성분의 설명력: 99.99%
제2주성분의 설명력: 0.01%
